# Generated by Django 2.0.6 on 2018-07-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='club_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
