# Generated by Django 2.0.6 on 2018-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0002_clubinfo_club_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=100, unique=True)),
                ('date', models.CharField(max_length=100)),
                ('info', models.CharField(blank=True, max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
