# Generated by Django 2.0.6 on 2018-07-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0003_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='roll_number',
            field=models.CharField(max_length=100),
        ),
    ]
