# Generated by Django 2.0.6 on 2018-07-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0004_auto_20180710_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
