# Generated by Django 2.0.6 on 2018-07-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0006_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='club_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
