# Generated by Django 2.0.6 on 2018-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0007_admin_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='club',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
