# Generated by Django 2.0.6 on 2018-07-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0008_form_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='approval',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
