# Generated by Django 2.0.6 on 2018-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0009_form_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(max_length=10)),
            ],
        ),
    ]
