# Generated by Django 2.0.6 on 2018-07-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0011_auto_20180712_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
