# Generated by Django 2.0.6 on 2018-07-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0013_auto_20180713_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='club',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
