# Generated by Django 2.0.6 on 2018-07-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalapp', '0014_auto_20180713_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='club',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
